esphome:
  name: ${name}
  friendly_name: Energy Meter DDS665 (ModBus RTU)
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.0.100
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0

uart:
  id: uart_modbus_server
  baud_rate: 9600
  tx_pin: 19
  rx_pin: 18
  stop_bits: 1
  parity: NONE # Works for me, to be checked DDS665 the doc says EVEN...  

modbus:
  uart_id: uart_modbus_server
  id: modbus_server
  flow_control_pin: 4
  send_wait_time: 1000ms

modbus_controller:
  - id: earu_dds665
    address: 0x1
    modbus_id: modbus_server
    setup_priority: -10
    update_interval: 2s

sensor:
  # Voltage section, Phase A, B, C as per the EA777 markings, Can also be named L1, L2, L3
  # In Volts, precision 0.1V
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: voltage
    name: "Voltage"
    address: 0x0000
    register_type: read
    register_count: 2
    accuracy_decimals: 1
    value_type: FP32
    unit_of_measurement: "V"

  # Current section in Amperes, precision 0.1A
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: current
    name: "Current"
    address: 0x0002
    register_type: read
    register_count: 2
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "A"

  # Active power in Watts: Total, Phases A, B, C
  # Precision 1W
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: active_power
    name: "Active power"
    address: 0x0004
    register_type: read
    register_count: 2
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "W"

  # Power factor, cos phi
  # Range 0-1.000, precision 0.001
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: power_factor
    name: "Power factor"
    address: 0x0006
    register_type: read
    register_count: 2
    accuracy_decimals: 3
    value_type: FP32
    unit_of_measurement: "cos Ï†"

  # Frequency, Hertz, precision 0.01Hz
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: frequency
    name: "Frequency"
    address: 0x000E
    register_type: read
    register_count: 2
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "Hz"

  # Energy
  - platform: modbus_controller
    modbus_controller_id: earu_dds665
    id: current_total_active_energy
    name: "Total active energy"
    address: 0x0100
    register_type: read
    register_count: 2
    accuracy_decimals: 2
    value_type: FP32
    unit_of_measurement: "kWh"